In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
print(Path.cwd())

C:\Users\ayush\Downloads\Farm_Analytics_Project

In [3]:
raw_path = Path("data/raw")

print(raw_path.exists())

True

In [4]:
for file in raw_path.iterdir():
    print(file.name)

Activity Master.xlsx
Farm A.xlsx
Farm B.xlsx
Farm C.xlsx
Vendor Master.xlsx

In [6]:
farm_a = pd.read_excel(raw_path / "Farm A.xlsx")
farm_b = pd.read_excel(raw_path / "Farm B.xlsx")
farm_c = pd.read_excel(raw_path / "Farm C.xlsx")

vendor_master = pd.read_excel(raw_path / "Vendor Master.xlsx")
activity_master = pd.read_excel(raw_path / "Activity Master.xlsx")

In [7]:
print("Farm A:", farm_a.shape)
print("Farm B:", farm_b.shape)
print("Farm C:", farm_c.shape)
print("Vendor Master:", vendor_master.shape)
print("Activity Master:", activity_master.shape)

Farm A: (57, 16)
Farm B: (172, 17)
Farm C: (166, 17)
Vendor Master: (5, 3)
Activity Master: (5, 2)

In [8]:
farm_a.head()

,ID & Farm Name,Date,Vendor ID,Activity ID,Crop ID,Crop Name,Water Used (L),Nutrient Used (ml),Energy Used (kWh),Temperature (°C),Humidity (%),pH,EC (mS/cm),Yield (kg),Status,Location
0,fa001 farm a,2026-06-01,V002,AC01,C001,Lettuce,420.0,180.0,12.5,24.2,68.0,6.1,1.2,0.0,Done,Pune
1,fa002 farm a,2026-06-02,V003,AC02,C003,Cucumber,480.0,200.0,13.2,25.0,65.0,6.0,1.5,0.0,Done,Pune
2,fa003 farm a,2026-06-03,V005,AC03,C001,Lettuce,460.0,190.0,12.8,25.3,66.0,6.2,1.4,0.0,Done,Pune
3,fa004 farm a,2026-06-04,V002,AC03,C003,Cucumber,350.0,150.0,10.8,23.8,70.0,6.0,1.3,0.0,Done,Pune
4,fa005 farm a,2026-06-05,V004,AC01,C004,Spinach,310.0,120.0,9.5,24.5,67.0,6.1,1.2,0.0,Done,Pune

In [9]:
farm_b.head()

,ID & Farm Name,Date,Vendor ID,Activity ID,Crop ID,Crop Name,Water Used (L),Nutrient Used (ml),Energy Used (kWh),Temperature (°C),Humidity (%),pH,EC (mS/cm),Yield (kg),Labor Hours,Status,Location
0,fb001 farm b,2026-04-01,V002,AC05,C002,Tomato,440.0,185.0,12.8,24.5,67.0,6.1,1.25,0.0,4.0,Done,Nashik
1,fb002 farm b,2026-04-02,V005,AC02,C004,Spinach,510.0,220.0,14.0,25.2,64.0,6.0,1.55,0.0,3.5,Done,Nashik
2,fb003 farm b,2026-04-03,V001,AC03,C001,Lettuce,480.0,200.0,13.2,25.5,65.0,6.2,1.48,0.0,3.0,Done,Nashik
3,fb004 farm b,2026-04-04,V002,AC04,C001,Lettuce,370.0,155.0,11.0,24.0,70.0,6.0,1.32,0.0,3.0,Done,Nashik
4,fb005 farm b,2026-04-05,V003,AC03,C003,Cucumber,540.0,0.0,14.5,24.6,67.0,6.1,1.28,105.0,5.0,Done,Nashik

In [10]:
farm_c.head()

,ID & Farm Name,Date,Vendor ID,Activity ID,Crop ID,Crop Name,Water Used (L),Nutrient Used (ml),Energy Used (kWh),Temperature (°C),Humidity (%),pH,EC (mS/cm),Yield (kg),Labor Hours,Status,Location
0,fc001 farm c,2026-06-01,V001,AC01,C001,Lettuce,407.0,189.0,12.5,24.7,67.0,6.2,1.25,0.0,4.0,Done,Satara
1,fc002 farm c,2026-06-02,V003,AC04,C003,Cucumber,504.0,232.0,14.3,25.4,64.0,6.0,1.55,0.0,3.0,Done,Satara
2,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,fc003 farm c,2026-06-03,V005,AC01,C003,Cucumber,540.0,253.0,15.0,26.0,65.0,6.1,1.50,0.0,3.5,Done,Satara
4,fc004 farm c,2026-06-04,V003,AC01,C001,Lettuce,390.0,164.0,10.8,24.1,73.0,6.0,1.32,0.0,2.5,Pending,Satara

In [11]:
vendor_master.head()

  Vendor ID        Vendor Name Vendor Category
0      V001     GreenGrow Agro      Fertilizer
1      V002     Aqua Solutions      Irrigation
2      V003           AgroCare       Pesticide
3      V004  FarmTech Supplies       Equipment
4      V005     FreshCrop Agro           Seeds

In [12]:
activity_master.head()

  Activity ID                 Activity
0        AC01               Irrigation
1        AC02              Fertigation
2        AC03  Cleaning & Sanitization
3        AC04       Climate Monitoring
4        AC05    Plant Health Scouting

In [13]:
farm_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID & Farm Name      51 non-null     object
 1   Date                51 non-null     datetime64[ns]
 2   Vendor ID           51 non-null     object
 3   Activity ID         51 non-null     object
 4   Crop ID             51 non-null     object
 5   Crop Name           51 non-null     object
 6   Water Used (L)      51 non-null     float64
 7   Nutrient Used (ml)  51 non-null     float64
 8   Energy Used (kWh)   51 non-null     float64
 9   Temperature (°C)    51 non-null     float64
 10  Humidity (%)        51 non-null     float64
 11  pH                  51 non-null     float64
 12  EC (mS/cm)          51 non-null     float64
 13  Yield (kg)          51 non-null     float64
 14  Status              51 non-null     object
 15  Location            51 non-null     object
dtypes: datetime64[ns](1), float64(8), object(7)
memory usage: 7.2+ KB

In [14]:
farm_a.isnull().sum()

ID & Farm Name        6
Date                  6
Vendor ID             6
Activity ID           6
Crop ID               6
Crop Name             6
Water Used (L)        6
Nutrient Used (ml)    6
Energy Used (kWh)     6
Temperature (°C)      6
Humidity (%)          6
pH                    6
EC (mS/cm)            6
Yield (kg)            6
Status                6
Location              6
dtype: int64

In [15]:
farm_b.isnull().sum()

ID & Farm Name        11
Date                  11
Vendor ID             11
Activity ID           11
Crop ID               11
Crop Name             11
Water Used (L)        11
Nutrient Used (ml)    11
Energy Used (kWh)     11
Temperature (°C)      11
Humidity (%)          11
pH                    11
EC (mS/cm)            11
Yield (kg)            11
Labor Hours           11
Status                11
Location              11
dtype: int64

In [16]:
farm_c.isnull().sum()

ID & Farm Name        9
Date                  9
Vendor ID             9
Activity ID           9
Crop ID               9
Crop Name             9
Water Used (L)        9
Nutrient Used (ml)    9
Energy Used (kWh)     9
Temperature (°C)      9
Humidity (%)          9
pH                    9
EC (mS/cm)            9
Yield (kg)            9
Labor Hours           9
Status                9
Location              9
dtype: int64

In [17]:
print("Farm A duplicates:", farm_a.duplicated().sum())
print("Farm B duplicates:", farm_b.duplicated().sum())
print("Farm C duplicates:", farm_c.duplicated().sum())

Farm A duplicates: 11
Farm B duplicates: 21
Farm C duplicates: 15

In [18]:
for name, df in {
    "Farm A": farm_a,
    "Farm B": farm_b,
    "Farm C": farm_c
}.items():

    print("\n", "=" * 40)
    print(name)
    print("=" * 40)

    print("Shape:", df.shape)
    print("Missing values:")
    print(df.isnull().sum())

    print("\nDuplicates:", df.duplicated().sum())

 ========================================
Farm A
========================================
Shape: (57, 16)
Missing values:
ID & Farm Name        6
Date                  6
Vendor ID             6
Activity ID           6
Crop ID               6
Crop Name             6
Water Used (L)        6
Nutrient Used (ml)    6
Energy Used (kWh)     6
Temperature (°C)      6
Humidity (%)          6
pH                    6
EC (mS/cm)            6
Yield (kg)            6
Status                6
Location              6
dtype: int64

Duplicates: 11

 ========================================
Farm B
========================================
Shape: (172, 17)
Missing values:
ID & Farm Name        11
Date                  11
Vendor ID             11
Activity ID           11
Crop ID               11
Crop Name             11
Water Used (L)        11
Nutrient Used (ml)    11
Energy Used (kWh)     11
Temperature (°C)      11
Humidity (%)          11
pH                    11
EC (mS/cm)            11
Yield (kg)            11
Labor Hours           11
Status                11
Location              11
dtype: int64

Duplicates: 21

 ========================================
Farm C
========================================
Shape: (166, 17)
Missing values:
ID & Farm Name        9
Date                  9
Vendor ID             9
Activity ID           9
Crop ID               9
Crop Name             9
Water Used (L)        9
Nutrient Used (ml)    9
Energy Used (kWh)     9
Temperature (°C)      9
Humidity (%)          9
pH                    9
EC (mS/cm)            9
Yield (kg)            9
Labor Hours           9
Status                9
Location              9
dtype: int64

Duplicates: 15

In [19]:
farm_a = farm_a.dropna(how="all")
farm_b = farm_b.dropna(how="all")
farm_c = farm_c.dropna(how="all")

In [20]:
print(farm_a.shape)
print(farm_b.shape)
print(farm_c.shape)

(51, 16)
(161, 17)
(157, 17)

In [21]:
farm_a = farm_a.drop_duplicates()
farm_b = farm_b.drop_duplicates()
farm_c = farm_c.drop_duplicates()

In [22]:
print("Farm A:", farm_a.shape)
print("Farm B:", farm_b.shape)
print("Farm C:", farm_c.shape)

Farm A: (45, 16)
Farm B: (150, 17)
Farm C: (150, 17)

In [23]:
farm_a["Labor Hours"] = np.nan

In [24]:
print(farm_a.columns)
print(farm_b.columns)
print(farm_c.columns)

Index(['ID & Farm Name', 'Date', 'Vendor ID', 'Activity ID', 'Crop ID',
       'Crop Name', 'Water Used (L)', 'Nutrient Used (ml)',
       'Energy Used (kWh)', 'Temperature (°C)', 'Humidity (%)', 'pH',
       'EC (mS/cm)', 'Yield (kg)', 'Status', 'Location', 'Labor Hours'],
      dtype='object')
Index(['ID & Farm Name', 'Date', 'Vendor ID', 'Activity ID', 'Crop ID',
       'Crop Name', 'Water Used (L)', 'Nutrient Used (ml)',
       'Energy Used (kWh)', 'Temperature (°C)', 'Humidity (%)', 'pH',
       'EC (mS/cm)', 'Yield (kg)', 'Labor Hours', 'Status', 'Location'],
      dtype='object')
Index(['ID & Farm Name', 'Date', 'Vendor ID', 'Activity ID', 'Crop ID',
       'Crop Name', 'Water Used (L)', 'Nutrient Used (ml)',
       'Energy Used (kWh)', 'Temperature (°C)', 'Humidity (%)', 'pH',
       'EC (mS/cm)', 'Yield (kg)', 'Labor Hours', 'Status', 'Location'],
      dtype='object')

In [25]:
rename_columns = {
    "ID & Farm Name": "id_farm_name",
    "Date": "date",
    "Vendor ID": "vendor_id",
    "Activity ID": "activity_id",
    "Crop ID": "crop_id",
    "Crop Name": "crop_name",
    "Water Used (L)": "water_used_l",
    "Nutrient Used (ml)": "nutrient_used_ml",
    "Energy Used (kWh)": "energy_used_kwh",
    "Temperature (°C)": "temperature_c",
    "Humidity (%)": "humidity_pct",
    "pH": "ph",
    "EC (mS/cm)": "ec_ms_cm",
    "Yield (kg)": "yield_kg",
    "Labor Hours": "labor_hours",
    "Status": "status",
    "Location": "location"
}

In [26]:
farm_a = farm_a.rename(columns=rename_columns)
farm_b = farm_b.rename(columns=rename_columns)
farm_c = farm_c.rename(columns=rename_columns)

In [27]:
farm_a.columns

Index(['id_farm_name', 'date', 'vendor_id', 'activity_id', 'crop_id',
       'crop_name', 'water_used_l', 'nutrient_used_ml', 'energy_used_kwh',
       'temperature_c', 'humidity_pct', 'ph', 'ec_ms_cm', 'yield_kg', 'status',
       'location', 'labor_hours'],
      dtype='object')

In [28]:
def split_id_farm(df):
    
    split_data = df["id_farm_name"].astype(str).str.strip().str.split(
        n=1,
        expand=True
    )
    
    df["record_id"] = split_data[0].str.upper()
    df["farm_name"] = split_data[1].str.title()
    
    df = df.drop(columns=["id_farm_name"])
    
    return df

In [29]:
farm_a = split_id_farm(farm_a)
farm_b = split_id_farm(farm_b)
farm_c = split_id_farm(farm_c)

In [30]:
farm_a[["record_id", "farm_name"]].head()

  record_id farm_name
0     FA001    Farm A
1     FA002    Farm A
2     FA003    Farm A
3     FA004    Farm A
4     FA005    Farm A

In [31]:
text_columns = [
    "vendor_id",
    "activity_id",
    "crop_id",
    "crop_name",
    "status",
    "location",
    "farm_name"
]

for df in [farm_a, farm_b, farm_c]:
    for col in text_columns:
        df[col] = df[col].astype(str).str.strip()

In [32]:
for df in [farm_a, farm_b, farm_c]:
    
    df["vendor_id"] = df["vendor_id"].str.upper()
    df["activity_id"] = df["activity_id"].str.upper()
    df["crop_id"] = df["crop_id"].str.upper()
    
    df["crop_name"] = df["crop_name"].str.title()
    df["status"] = df["status"].str.title()
    df["location"] = df["location"].str.title()

In [33]:
for df in [farm_a, farm_b, farm_c]:
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [34]:
farm_a.dtypes

date                datetime64[ns]
vendor_id                   object
activity_id                 object
crop_id                     object
crop_name                   object
water_used_l               float64
nutrient_used_ml           float64
energy_used_kwh            float64
temperature_c              float64
humidity_pct               float64
ph                         float64
ec_ms_cm                   float64
yield_kg                   float64
status                      object
location                    object
labor_hours                float64
record_id                   object
farm_name                   object
dtype: object

In [35]:
farm_data = pd.concat(
    [farm_a, farm_b, farm_c],
    ignore_index=True
)

In [36]:
farm_data.shape

(345, 18)

In [37]:
farm_data.duplicated().sum()

0

In [38]:
farm_data["record_id"].duplicated().sum()

0

In [39]:
vendor_master = vendor_master.rename(columns={
    "Vendor ID": "vendor_id",
    "Vendor Name": "vendor_name",
    "Vendor Category": "vendor_category"
})

In [40]:
for col in ["vendor_id", "vendor_name", "vendor_category"]:
    vendor_master[col] = vendor_master[col].astype(str).str.strip()

In [41]:
vendor_master

  vendor_id        vendor_name vendor_category
0      V001     GreenGrow Agro      Fertilizer
1      V002     Aqua Solutions      Irrigation
2      V003           AgroCare       Pesticide
3      V004  FarmTech Supplies       Equipment
4      V005     FreshCrop Agro           Seeds

In [42]:
activity_master = activity_master.rename(columns={
    "Activity ID": "activity_id",
    "Activity": "activity"
})

In [43]:
for col in ["activity_id", "activity"]:
    activity_master[col] = activity_master[col].astype(str).str.strip()

In [44]:
activity_master

  activity_id                 activity
0        AC01               Irrigation
1        AC02              Fertigation
2        AC03  Cleaning & Sanitization
3        AC04       Climate Monitoring
4        AC05    Plant Health Scouting

In [45]:
farm_data = farm_data.merge(
    vendor_master,
    on="vendor_id",
    how="left",
    validate="many_to_one"
)

In [46]:
farm_data.head()

,date,vendor_id,activity_id,crop_id,crop_name,water_used_l,nutrient_used_ml,energy_used_kwh,temperature_c,humidity_pct,ph,ec_ms_cm,yield_kg,status,location,labor_hours,record_id,farm_name,vendor_name,vendor_category
0,2026-06-01,V002,AC01,C001,Lettuce,420.0,180.0,12.5,24.2,68.0,6.1,1.2,0.0,Done,Pune,NaN,FA001,Farm A,Aqua Solutions,Irrigation
1,2026-06-02,V003,AC02,C003,Cucumber,480.0,200.0,13.2,25.0,65.0,6.0,1.5,0.0,Done,Pune,NaN,FA002,Farm A,AgroCare,Pesticide
2,2026-06-03,V005,AC03,C001,Lettuce,460.0,190.0,12.8,25.3,66.0,6.2,1.4,0.0,Done,Pune,NaN,FA003,Farm A,FreshCrop Agro,Seeds
3,2026-06-04,V002,AC03,C003,Cucumber,350.0,150.0,10.8,23.8,70.0,6.0,1.3,0.0,Done,Pune,NaN,FA004,Farm A,Aqua Solutions,Irrigation
4,2026-06-05,V004,AC01,C004,Spinach,310.0,120.0,9.5,24.5,67.0,6.1,1.2,0.0,Done,Pune,NaN,FA005,Farm A,FarmTech Supplies,Equipment

In [47]:
farm_data = farm_data.merge(
    activity_master,
    on="activity_id",
    how="left",
    validate="many_to_one"
)

In [48]:
farm_data.head()

,date,vendor_id,activity_id,crop_id,crop_name,water_used_l,nutrient_used_ml,energy_used_kwh,temperature_c,humidity_pct,...,ec_ms_cm,yield_kg,status,location,labor_hours,record_id,farm_name,vendor_name,vendor_category,activity
0,2026-06-01,V002,AC01,C001,Lettuce,420.0,180.0,12.5,24.2,68.0,...,1.2,0.0,Done,Pune,NaN,FA001,Farm A,Aqua Solutions,Irrigation,Irrigation
1,2026-06-02,V003,AC02,C003,Cucumber,480.0,200.0,13.2,25.0,65.0,...,1.5,0.0,Done,Pune,NaN,FA002,Farm A,AgroCare,Pesticide,Fertigation
2,2026-06-03,V005,AC03,C001,Lettuce,460.0,190.0,12.8,25.3,66.0,...,1.4,0.0,Done,Pune,NaN,FA003,Farm A,FreshCrop Agro,Seeds,Cleaning & Sanitization
3,2026-06-04,V002,AC03,C003,Cucumber,350.0,150.0,10.8,23.8,70.0,...,1.3,0.0,Done,Pune,NaN,FA004,Farm A,Aqua Solutions,Irrigation,Cleaning & Sanitization
4,2026-06-05,V004,AC01,C004,Spinach,310.0,120.0,9.5,24.5,67.0,...,1.2,0.0,Done,Pune,NaN,FA005,Farm A,FarmTech Supplies,Equipment,Irrigation

In [49]:
farm_data["vendor_name"].isnull().sum()

0

In [50]:
farm_data["activity"].isnull().sum()

0

In [51]:
farm_data.isnull().sum()

date                 0
vendor_id            0
activity_id          0
crop_id              0
crop_name            0
water_used_l         0
nutrient_used_ml     0
energy_used_kwh      0
temperature_c        0
humidity_pct         0
ph                   0
ec_ms_cm             0
yield_kg             0
status               0
location             0
labor_hours         45
record_id            0
farm_name            0
vendor_name          0
vendor_category      0
activity             0
dtype: int64

In [52]:
farm_data.describe()

,water_used_l,nutrient_used_ml,energy_used_kwh,temperature_c,humidity_pct,ph,ec_ms_cm,yield_kg,labor_hours
count,345.000000,345.000000,345.000000,345.000000,345.000000,345.000000,345.000000,345.000000,300.000000
mean,493.078261,162.414493,13.570725,24.926087,67.513043,6.083188,1.415565,26.437681,3.710000
std,84.680674,89.477614,1.820837,0.680512,3.071905,0.081456,0.110954,52.688116,0.899219
min,300.000000,0.000000,9.200000,23.800000,63.000000,5.900000,1.200000,0.000000,2.000000
25%,430.000000,155.000000,12.200000,24.300000,65.000000,6.000000,1.300000,0.000000,3.000000
50%,500.000000,190.000000,13.600000,24.800000,67.000000,6.100000,1.390000,0.000000,3.500000
75%,560.000000,230.000000,15.000000,25.600000,69.000000,6.200000,1.500000,0.000000,4.000000
max,700.000000,280.000000,18.000000,26.000000,73.000000,6.200000,1.590000,182.000000,6.000000

In [53]:
farm_data["month"] = farm_data["date"].dt.to_period("M").astype(str)

In [54]:
farm_data["year"] = farm_data["date"].dt.year

In [55]:
farm_data["month_name"] = farm_data["date"].dt.month_name()

In [56]:
farm_data["yield_per_100l_water"] = np.where(
    farm_data["water_used_l"] > 0,
    (farm_data["yield_kg"] / farm_data["water_used_l"]) * 100,
    np.nan
)

In [57]:
farm_data["yield_per_kwh"] = np.where(
    farm_data["energy_used_kwh"] > 0,
    farm_data["yield_kg"] / farm_data["energy_used_kwh"],
    np.nan
)

In [58]:
print("Rows:", farm_data.shape[0])
print("Columns:", farm_data.shape[1])

print("\nDuplicates:")
print(farm_data.duplicated().sum())

print("\nDuplicate IDs:")
print(farm_data["record_id"].duplicated().sum())

print("\nMissing values:")
print(farm_data.isnull().sum())

Rows: 345
Columns: 26

Duplicates:
0

Duplicate IDs:
0

Missing values:
date                     0
vendor_id                0
activity_id              0
crop_id                  0
crop_name                0
water_used_l             0
nutrient_used_ml         0
energy_used_kwh          0
temperature_c            0
humidity_pct             0
ph                       0
ec_ms_cm                 0
yield_kg                 0
status                   0
location                 0
labor_hours             45
record_id                0
farm_name                0
vendor_name              0
vendor_category          0
activity                 0
month                    0
year                     0
month_name               0
yield_per_100l_water     0
yield_per_kwh            0
dtype: int64

In [59]:
farm_data["yield_kg"].sum()

9121.0

In [60]:
farm_data["water_used_l"].sum()

170112.0

In [61]:
farm_data["energy_used_kwh"].sum()

4681.9

In [62]:
farm_data["temperature_c"].mean()

24.92608695652175

In [63]:
yield_by_farm = (
    farm_data
    .groupby("farm_name")["yield_kg"]
    .sum()
    .sort_values(ascending=False)
)

yield_by_farm

farm_name
Farm C    4461.0
Farm B    3770.0
Farm A     890.0
Name: yield_kg, dtype: float64

In [64]:
yield_by_crop = (
    farm_data
    .groupby("crop_name")["yield_kg"]
    .sum()
    .sort_values(ascending=False)
)

yield_by_crop

crop_name
Lettuce     3104.0
Spinach     2614.0
Cucumber    2474.0
Tomato       929.0
Name: yield_kg, dtype: float64

In [65]:
farm_data["status"].value_counts()

Done           284
Pending         36
In Progress     18
Delayed          7
Name: status, dtype: int64

In [66]:
monthly_yield = (
    farm_data
    .groupby("month")["yield_kg"]
    .sum()
    .reset_index()
)

monthly_yield

     month  yield_kg
0  2026-04     215.0
1  2026-05     435.0
2  2026-06    2303.0
3  2026-07    3193.0
4  2026-08    2975.0

In [67]:
cleaned_path = Path("data/cleaned")
cleaned_path.mkdir(parents=True, exist_ok=True)

In [68]:
farm_data.to_csv(
    cleaned_path / "cleaned_farm_data.csv",
    index=False
)